# Generated by Django 4.2.3 on 2023-07-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_practiceuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeUser',
            new_name='Practice',
        ),
    ]
