# Generated by Django 4.2.3 on 2023-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='het@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default='het', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='phone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='email',
            field=models.EmailField(default='het@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='name',
            field=models.CharField(default='het', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='phone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
