# Generated by Django 4.2.3 on 2023-07-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_click_delete_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Click',
            new_name='Add_Click1',
        ),
    ]
