# Generated by Django 4.2.3 on 2023-07-18 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_add_click_add_click1'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_click1',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
