# Generated by Django 4.2.3 on 2023-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_click1_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_click1',
            old_name='r1',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='add_click1',
            name='t_desc',
            field=models.CharField(max_length=50),
        ),
    ]
