# Generated by Django 4.2.3 on 2023-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_r1_add_click1_status_alter_add_click1_t_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Click1',
            new_name='Tasks',
        ),
    ]
