# Generated by Django 4.2.3 on 2023-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_add_click1_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pract_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
