# Generated by Django 4.2.3 on 2023-07-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Furniture_name', models.CharField(max_length=10)),
                ('Furniture_desc', models.CharField(max_length=30)),
                ('Furniture_modelno', models.IntegerField()),
                ('Furniture_cat', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
    ]
