# Generated by Django 4.2.3 on 2023-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_furnitureinfo_delete_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureinfo',
            name='Furniture_cat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='furnitureinfo',
            name='Furniture_desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='furnitureinfo',
            name='Furniture_name',
            field=models.CharField(max_length=30),
        ),
    ]
