# Generated by Django 4.2.3 on 2023-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureinfo',
            name='Furniture_modelno',
            field=models.PositiveIntegerField(),
        ),
    ]
